/**
 * Copies the flag artwork this app serves from /flag-art into public/flag-art.
 *
 * Why the files are vendored rather than imported from node_modules: the web
 * image is a Next standalone build, where anything not reachable from the
 * module graph has to be copied in by hand — public/ already is, and a plain
 * static directory cannot repeat the symlink problems the standalone output
 * gave us. The flags also change about as often as the countries do.
 *
 * Why this package rather than flag-icons: flag-icons only ships 4x3 and 1x1
 * renditions, and both are made by clipping the real flag to that box — Bosnia
 * and Herzegovina (1:2) loses its sides, Canada's bands are cut. These SVGs
 * keep each flag's official proportions, which is what a flag quiz is asking
 * the player to recognise.
 *
 * Run it from the repo root after changing the country list:
 *   pnpm --filter @cartomancer/shared build && pnpm --filter @cartomancer/web vendor:flags
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, copyFileSync, writeFileSync, rmSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { COUNTRIES } from '@cartomancer/shared';

// Pinned: a silent upstream redraw would change 195 committed files.
const PACKAGE = 'svg-country-flags@1.2.10';

const here = dirname(fileURLToPath(import.meta.url));
// Not public/flags: static files do serve under a page route's prefix today
// (checked against a running standalone build), but adding a /flags/[code]
// route later would shadow them, and that failure would show up as missing
// flags in production rather than at build time. The separate prefix costs
// nothing.
const outDir = join(here, '..', 'public', 'flag-art');

const work = mkdtempSync(join(tmpdir(), 'cartomancer-flags-'));
try {
  console.log(`Fetching ${PACKAGE}…`);
  const tarball = execFileSync('npm', ['pack', PACKAGE, '--pack-destination', work, '--silent'], {
    encoding: 'utf8',
  })
    .trim()
    .split('\n')
    .pop();
  execFileSync('tar', ['xzf', join(work, tarball), '-C', work]);

  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });

  const missing = [];
  for (const country of COUNTRIES) {
    const code = country.isoCode.toLowerCase();
    const from = join(work, 'package', 'svg', `${code}.svg`);
    try {
      copyFileSync(from, join(outDir, `${code}.svg`));
    } catch {
      missing.push(`${country.name} (${country.isoCode})`);
    }
  }

  if (missing.length > 0) {
    // A country without a flag would render as a broken image in a quiz whose
    // whole point is the flag, so this is fatal rather than a warning.
    throw new Error(`No flag artwork for:\n  ${missing.join('\n  ')}`);
  }

  writeFileSync(
    join(outDir, 'README.md'),
    [
      '# Flag artwork',
      '',
      `Generated by \`apps/web/scripts/vendor-flags.mjs\` from \`${PACKAGE}\`.`,
      'Do not edit these files by hand — re-run the script instead:',
      '',
      '```sh',
      'pnpm --filter @cartomancer/shared build',
      'pnpm --filter @cartomancer/web vendor:flags',
      '```',
      '',
      'The SVGs are the Wikimedia Commons flag renderings, which are in the',
      'public domain in most jurisdictions as government works or as simple',
      'geometry; the packaging is MIT-licensed. Each flag keeps its official',
      'proportions, which is the point: the 4x3 sets in common use clip wide',
      'flags to fit their box.',
      '',
      `${COUNTRIES.length} files, one per country in \`@cartomancer/shared\`.`,
      '',
    ].join('\n'),
  );

  const count = readdirSync(outDir).filter((f) => f.endsWith('.svg')).length;
  console.log(`Wrote ${count} flags to apps/web/public/flag-art.`);
} finally {
  rmSync(work, { recursive: true, force: true });
}
